# -*- coding: utf-8 -*-
"""Model Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QULK6ayHhKt9ro--h56zIaZJACCEpNMF
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.stem.porter import PorterStemmer
nltk.download('punkt')
nltk.download('punkt_tab')
import pickle

import kagglehub
# Download latest version
path = kagglehub.dataset_download("notshrirang/spotify-million-song-dataset")
print("Path to dataset files:", path)

df = pd.read_csv("dataset.csv")

df = df.sample(10000).drop("link",axis=1).reset_index(drop=True)

df['text'] = df['text'].str.lower().replace(r'^\w\s', '').replace(r'\n',' ',regex=True)

stemmer = PorterStemmer()

def token(txt):
    token = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in token]
    return " ".join(a)

df['text'].apply(lambda x:token(x))

tfid = TfidfVectorizer(analyzer='word',stop_words='english')

matrix = tfid.fit_transform(df['text'])

similer = cosine_similarity(matrix)

pickle.dump(similer,open('similer.pkl','wb'))
pickle.dump(df,open('df.pkl','wb'))